### ISSUE TITLE
Dashboard filter field domain

### ISSUE THREAD

**Issue by niyasraphy** [odoo/o-spreadsheet#1922]
Hi,
Looking for the option of how to filter field values by applying domain to the values shown in the dashboard filters.

![Screenshot from 2022-12-29 20-20-16](https://user-images.githubusercontent.com/27989791/209987486-374edf1d-34d9-4276-bf8d-c8b80059a837.png)

For example, sales persons field to show only internal users.

{
            "id": "4181e8e3-2e7e-42be-a88b-f24acb7d03e7",
            "type": "relation",
            "label": "Salespersonss",
            "modelName": "res.users",
            "defaultValue": [],
            "defaultValueDisplayNames": [],
            "rangeType": "year",
            "defaultsToCurrentPeriod": false,

Not sure if an option exists or not, looking for guidance on the same

**Comment by niyasraphy** [comment]
hi @rrahir ,
if you have time, can you guide on the same.
thanks

**Comment by rrahir** [comment]
This is not really supported atm because you can only apply a filter to the fields of the models to which the datasources (pivot/list/graph) apply. So for instance, is you load a pivot of model `sale.order`, you will not be able to apply a filter on a `res.group` because there are no fields on sale.order that refer to `res.group`.

As the example hints, there might be a way to cheat by inserting a datasource of the model res.users, then you could apply a filter to res.group and it so happens that the current design lets you apply that filter to all datasources.

However, there are 2 things about this:
1. The feature was not designed for this particular use, it's just a nice side effect, but I cannot guarantee that we will keep it this way in the future
2. keep in mind that the domains are submitted to the Odoo access rights. The res.groups might not be an issue in standard odoo but the more intricate the search domain becomes, the more likely you are to crash with the access rights, which would prevent users from seeing the data altogether.
